### ISSUE TITLE
How to run the a Singularity container within Neurodesktop so it will be writable?

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurocommand#107]
Hi @aswinnarayanan @stebo85 

In order to do some tests, I would like to run a Singularity container within Neurodesktop, but in a way that I can write inside the Singularity container (e.g., in order to install things for testing). I do not need persistency or anything like that, just permission to write in system folders where software is usually installed when running apt-get.
I tried to give Singularity various arguments like --writable, --fakeroot, --overlay, to name a few, but neither combination works. 
Is it possible to do what I want? How?

Thanks ahead,
Oren

**Comment by stebo85** [comment]
yes, this is possible and I regularly use this for testing and trying to figure out why containers don't build.

I build in a switch into the build.sh command to do this: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/main_setup.sh

Cheers
Steffen

**Comment by stebo85** [comment]
sudo singularity build --sandbox ${imageName}_${buildDate}.sif ${imageName}.Singularity

would give you a sandbox and then you need to shell into it with sudo as well (because most files in the sandbox are owned by root)

Another option is to use an overlay file:

singularity overlay create --size 1024 /tmp/ext3_overlay.img
singularity shell --overlay /tmp/ext3_overlay.img yourcontainer.img

**Comment by civier** [comment]
Thanks @stebo85 

BTW, will the --overlay option work also if yourcontainer.img is on the CVMFS? If not, is there another solution for containers on the CVMFS?

Best,
Oren

**Comment by stebo85** [comment]
Yes overlay also works for containers in CVMFS.

**Comment by civier** [comment]
@stebo85 I tried the overlay approach, but still "apt-get update" does not run successfuly.
What am I missing? (tried both with and without --fakeroot)
<img width="1680" alt="Screen Shot 2022-02-08 at 5 42 21 pm" src="https://user-images.githubusercontent.com/8280611/152932769-da460b33-08d2-4b28-bdc8-24660d8fd044.png">
Hope it's nothing silly I forgot :-(

**Comment by civier** [comment]
@stebo85  Got up to 'apt-get install sshfs', but something is still not working. Any clue how my setup is different than yours?

<img width="1680" alt="Screen Shot 2022-02-08 at 6 07 08 pm" src="https://user-images.githubusercontent.com/8280611/152935731-441017b6-ba70-4eeb-9ccc-c75b20d38f8c.png">

**Comment by stebo85** [comment]
Dear @civier - I don't think what you are trying is possible. I would in general advice against using sshfs. If you really must use it, then it would be better to mount this drive from the main container and then pass it through to the singularity container via bindmounts.

**Comment by civier** [comment]
Thanks for the quick response @stebo85

1. We use sshfs as a temporary solution and it works well for us. However, the problem is when it gets disconnected after all -- because Singularity bindmounts can only be set up at startup, it means that we need to restart the Singularity container, and it often not convenient to the user (e.g., if they have a GUI open with a specific layout or with specific files already loaded)
What is the general problem with running sshfs from within a Singularity container?

2. The sshfs is only one thing we would like to install within containers for testing / temporarily. You said that you do it often, so I wonder how?

**Comment by stebo85** [comment]
Dear @civier

As you noticed already yourself: SSHFS is not a stable way of connecting and this is the main reason I would not recommend it.

If you really need to run apt in an overlay you cannot use CVMFS, but you need to use the simg file:

```
export container=mrtrix3_3.0.3_20210917
curl -X GET https://objectstorage.ap-sydney-1.oraclecloud.com/n/sd63xuke79z3/b/neurodesk/o/${container}.simg -O
sudo singularity shell --overlay /tmp/ext3_overlay.img mrtrix3_3.0.3_20210917.simg
```

now you can run it:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/4021595/152952217-b054499d-27f1-4c1e-a4bd-c6ab023ef30f.png">

but again, I cannot recommend this in any way for production use
