### ISSUE TITLE
add a new line to apps.json to specify an additional mountpoint

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocommand#118]
the idea is to have an additional mountpoint so that we can mount an unwritable directory inside the container to a writable directory outside the container

This would solve our Matlab license problem that @civier is working on.

It would also solve our Slicer extension install problem

and it would solve our VScode extension problem

and the physio container issue: downloads examples when running run_spm12.sh /opt/mcr/v911/ tapas_download_example_data

**Comment by civier** [comment]
That sounds like a great idea!
Specifically with MATLAB, I need to see if there are any other files stored in the folder MATLAB tries to save the license to?

**Comment by stebo85** [comment]
related to neurodesktop#89

**Comment by civier** [comment]
> That sounds like a great idea! Specifically with MATLAB, I need to see if there are any other files stored in the folder MATLAB tries to save the license to?

@stebo85 Let me know when done, and I can test.

**Comment by stebo85** [comment]
It's already done @civier

**Comment by stebo85** [comment]
solved

**Comment by civier** [comment]
Hi Steffen,

Can you refer me to where it is documented how to specify the additional mountpoint in the apps.json file? I checked the current apps.json, and didn't see any such lines.

Or do you mean that you solved the MATLAB issue in a different way? How?

Best,
Oren

**Comment by stebo85** [comment]
Dear @civier,

We solved it by mounting the license directories via an entry in the .bashrc:

https://github.com/NeuroDesk/neurodesktop/blob/2ccdf46dee653402a6844b304c995644e1bb04be/config/.bashrc#L30

Kind regards 
Steffen
