### ISSUE TITLE
Add/update latest tag

### ISSUE THREAD

**Issue by stdweird** [NeuroDesk/neurocommand#121]
Linux instructions in https://www.neurodesk.org/docs/neurocommand/getting-started/linux/#command-line-mode-eg-running-on-an-hpc-or-cvl assume the latest commit in this repo is always working.

Ideally, a github action is added to the current testing actions that sets/updates a latest tag that can be used instead. Right now, simple typo in main and some bad timing could mean that stuff is broken.

Some googling gave eg https://github.com/EndBug/latest-tag (which i have never tested/used) as an example

**Comment by stebo85** [comment]
Dear @stdweird - thank you for raising this issue.

I would like to propose the following solution: We protect the master branch of neurcommand and it's only possible to merge changes if our unitests pass. 

@aswinnarayanan - any thoughts on this?

Thank you
Steffen

**Comment by stebo85** [comment]
I now protected the main branch. It's not possible anymore to directly commit to main and everything has to go via a pull request with approval. To be able to merge our unittests have to pass. 

I am testing this now and once it seems all working I close this issue :)

Sorry again for breaking your workflow @stdweird - this should hopefully not happen again so easily (assuming our unittests cover everything :)). I am very interested to hear more about what you are doing with neurocommand in your project -> would you have time for a quick chat in october?

**Comment by stebo85** [comment]
@aswinnarayanan - one little hickup: With the new protected main branch the autocommit doesn't work anymore. Any idea to push the changes directly to the website without committing it back to neurocommand :?

**Comment by stebo85** [comment]
@aswinnarayanan, I found a workaround: I had to create a personal access token for the commit and this commit can now skip the branch protection. Needs more testing and I hope this works.

**Comment by stdweird** [comment]
@stebo85 thanks for improving/protecting the flow. a chat is ok for me, but don't expect anything fancy ;) you can PM me with some dates.

**Comment by stebo85** [comment]
closing this, because the protected branch feature and automated unit testing before merges get accepted solves this issues elegantly
