### ISSUE TITLE
Sydney cvmfs objectstorage missing containers

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurocommand#162]
@stebo85 

The Sydney object storage is missing some of the newer containers.
While Ashburn and Frankfurt object storage are fully in sync.

I'm investigating now, but let me know if you have any ideas

**Comment by stebo85** [comment]
oh, not good - let me check what's happening there and add a test as well - because it didn't get flagged anywhere?

**Comment by stebo85** [comment]
fixed (token had to be updated) and tests are now added so we should be alerted if it happens again :)
