### ISSUE TITLE
neurocommand doesn't update the menu on play / lab

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocommand#165]
The update runs without errors, but new menu entries are not added on the jupyter instances. It works in docker and nectar vdi though. 

Any ideas what that could be?

**Comment by aswinnarayanan** [comment]
Interesting, Its supposed to update on desktop startup. The play instance i opened is up to date with 2 days ago, which is odd

**Comment by aswinnarayanan** [comment]
![image](https://user-images.githubusercontent.com/25297584/222637610-c9744cb0-a635-4cf5-8c96-6d73f7b1ac37.png)

Is this the latest container?

**Comment by stebo85** [comment]
Yes the latest afni container was the one I tested it with

**Comment by stebo85** [comment]
Ahh - the desktop updates on restart but not when clicking update in the menu

**Comment by stebo85** [comment]
does this require a reload of the menu and should this be included in the update script?

**Comment by stebo85** [comment]
I think I found the problem. The update script doesn't pull the github repository:

changing
```
#!/usr/bin/env bash
 cd /neurocommand/local/neurocommand; bash build.sh; read -p "Press enter to close this window ..."

```

to
```
#!/usr/bin/env bash
 cd /neurocommand/local/neurocommand; git pull; bash build.sh; read -p "Press enter to close this window ..."

```

seems to fix the problem

**Comment by stebo85** [comment]
attempted to fix here: https://github.com/NeuroDesk/neurocommand/commit/592205c7f38c567cc606f83b67b68d95abce3439
