### ISSUE TITLE
issues contributing tutorials/building github pages

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurocommand#195]
Hey team,

Hope you are having a fine Monday :)

I am having issues building the website with my tutorial edits in. 

I made my edits and then merged by tutorial branch with the hugo-docsy branch and then pushed the changes to my forked repo. I fetched upstream changes before I pushed. 

Now, when I go to "Actions" I don't get an option to enable actions (i.e no "I understand my workflows..."), I instead see a list of All workflows.

When I go to Pages, the settings do point to gh-pages, however when I click the link for the site, I don't see my changes, but rather the old version.

Have I missed a step somewhere?

All info much appreciated!

**Comment by stebo85** [comment]
looks like this is solved now. @iishiishii and @kel-github does it need more documentation to prevent this problem in the future?

**Comment by iishiishii** [comment]
Ah I didn't see this thread. You can run the workflow if clicking on each of them. The button is hidden when there are multiple workflows.

![image](https://github.com/NeuroDesk/neurocommand/assets/59903692/bfd9b72c-d8e1-4835-a898-4234aa42e072)

**Comment by stebo85** [comment]
Can you add this to the documentation?
