### ISSUE TITLE
installation instructions missing from getting started

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurocommand#196]
Hey folks, 
FYI, I noticed that the https://www.neurodesk.org/docs/getting-started/neurodesktop/neurodeskapp/ page doesn't contain installation instructions - e.g. there is a link to the deb file etc, but no instructions on what to do with that file once you have it (e.g. sudo dpkg -i etc). I've pasted the text below.

Installing Neurodesk App

If you have an existing Neurodesk App installation, please first uninstall it by following the uninstall instructions [here](https://www.neurodesk.org/docs/getting-started/neurodesktop/neurodeskapp/#uninstalling-neurodesk-app). Then, follow the installation instructions below:

    [Debian, Ubuntu Linux Installer](https://github.com/NeuroDesk/neurodesk-app/releases/latest/download/NeurodeskApp-Setup-Debian.deb)

**Comment by stebo85** [comment]
great find - thank you!  it's added now :)
