### ISSUE TITLE
Centrally managed neurocommands

### ISSUE THREAD

**Issue by marcelzwiers** [NeuroDesk/neurocommand#261]
Installing neurocommands on our HPC works as expected, following the instructions from the documentation. This installs modules and containers in the user directory. What I would like to do is:

* Install it for all HPC users, e.g. in `/opt/neurocommand/`. Can I ask our sys admin to do just that or is there something that needs to be adapted (e.g. the build script)?
* Install it without changing the Python base environment. I know that can be done using venv (or conda or so), but would that require users to activate that environment before running neurocommands? Or is the Python venv not needed to run neurocommands and can I simply run the build script in the venv, fetch containers, deactivate it, and then load the module and run neurocommands in the base environment?

**Comment by marcelzwiers** [comment]
Thanks! Our /opt is mounted on all nodes, and yes, it would be nice if the
installation docs mention that the requirements are not needed for using
the containers, and that one best installs the python libs in a venv.
Thanks again, I will try to make things available centre wide, and will let
you know if we encounter issues. Cheers from Nijmegen :)

_____________________
Sent from my phone

Op ma 29 jan 2024 23:40 schreef Steffen Bollmann ***@***.***>:

**Comment by stebo85** [comment]
Great :) I added more details to the documentation.
